// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Placeful.Api.Data;

#nullable disable

namespace Placeful.Api.Migrations
{
    [DbContext(typeof(PlacefulDbContext))]
    [Migration("20251011150413_AddUserProfileIdToMemoryMigration")]
    partial class AddUserProfileIdToMemoryMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Placeful.Api.Models.Entities.FavoriteMemoriesList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteMemoriesLists");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid?>("FavoriteMemoriesListId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteMemoriesListId");

                    b.HasIndex("LocationId");

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.UserFriendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("FriendshipAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("FriendshipInitiatorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FriendshipReceiverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FriendshipInitiatorId");

                    b.HasIndex("FriendshipReceiverId");

                    b.ToTable("UserFriendships");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("FavoritesMemoriesListId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FavoritesMemoriesListId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.Memory", b =>
                {
                    b.HasOne("Placeful.Api.Models.Entities.FavoriteMemoriesList", null)
                        .WithMany("Memories")
                        .HasForeignKey("FavoriteMemoriesListId");

                    b.HasOne("Placeful.Api.Models.Entities.Location", "Location")
                        .WithMany("Memories")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.UserFriendship", b =>
                {
                    b.HasOne("Placeful.Api.Models.Entities.UserProfile", "FriendshipInitiator")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("FriendshipInitiatorId")
                        .HasPrincipalKey("FirebaseUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Placeful.Api.Models.Entities.UserProfile", "FriendshipReceiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("FriendshipReceiverId")
                        .HasPrincipalKey("FirebaseUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FriendshipInitiator");

                    b.Navigation("FriendshipReceiver");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.UserProfile", b =>
                {
                    b.HasOne("Placeful.Api.Models.Entities.FavoriteMemoriesList", "FavoritesMemoriesList")
                        .WithMany()
                        .HasForeignKey("FavoritesMemoriesListId");

                    b.HasOne("Placeful.Api.Models.Entities.UserProfile", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("FavoritesMemoriesList");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.FavoriteMemoriesList", b =>
                {
                    b.Navigation("Memories");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.Location", b =>
                {
                    b.Navigation("Memories");
                });

            modelBuilder.Entity("Placeful.Api.Models.Entities.UserProfile", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
