// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Placeful.Api.Data;

#nullable disable

namespace Placeful.Api.Migrations
{
    [DbContext(typeof(PlacefulDbContext))]
    [Migration("20250913112619_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Placeful.Api.Models.FavoriteMemoriesList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("FavoritesLists");
                });

            modelBuilder.Entity("Placeful.Api.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Placeful.Api.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Placeful.Models.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("Placeful.Api.Models.FavoriteMemoriesList", b =>
                {
                    b.HasOne("Placeful.Models.Memory", "Memory")
                        .WithMany()
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Placeful.Api.Models.UserProfile", "UserProfile")
                        .WithOne("FavoritesMemoriesList")
                        .HasForeignKey("Placeful.Api.Models.FavoriteMemoriesList", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Placeful.Api.Models.UserProfile", b =>
                {
                    b.HasOne("Placeful.Api.Models.UserProfile", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserProfileId");
                });

            modelBuilder.Entity("Placeful.Models.Memory", b =>
                {
                    b.HasOne("Placeful.Api.Models.Location", "Location")
                        .WithMany("Memories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Placeful.Api.Models.Location", b =>
                {
                    b.Navigation("Memories");
                });

            modelBuilder.Entity("Placeful.Api.Models.UserProfile", b =>
                {
                    b.Navigation("FavoritesMemoriesList")
                        .IsRequired();

                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
